### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by Ovaday** [Ovaday/DEEMa#23]
- [x] we need to create tickets to implement everything that we discuss.
- [x] Daria will find for us a room for meeting in a university: https://github.com/Ovaday/DEEMa/issues/25
- [x] google about Industrial Data Management (what do they do): https://github.com/Ovaday/DEEMa/issues/30 
- [x] make list of past year projects * pros and cons * One person makes a list, everybody reviews and writes the summary why he likes or don't. Further discuss: https://github.com/Ovaday/DEEMa/issues/29 
- [x] everyone writes his own personal values, his own vision, mission, purpose. First take a look at what Daria will send to us. Then to write about it. Than to think about the values for our project. Save it to one list, to discuss further: https://github.com/Ovaday/DEEMa/issues/32
- [ ] add animations to the website: https://github.com/Ovaday/DEEMa/issues/27
- [ ] add cookies & security popup - on bottom, consents: https://github.com/Ovaday/DEEMa/issues/31
- [x] create a logo: https://github.com/Ovaday/DEEMa/issues/22
- [ ] accessibility things: to https://github.com/Ovaday/DEEMa/issues/28
- [x] we need to meet to discuss everything.

**Comment by Ovaday** [comment]
Twitter page

**Comment by Ovaday** [comment]
Social media manager

**Comment by Ovaday** [comment]
- [ ] to select a final name
- [ ]
